import sys

import pandas as pd
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QMessageBox, QMainWindow, QApplication

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LPIApp(object):
    def setupUi(self, LPIApp):
        LPIApp.setObjectName("LPIApp")
        LPIApp.resize(1123, 1018)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        LPIApp.setPalette(palette)
        self.listWidget = QtWidgets.QListWidget(parent=LPIApp)
        self.listWidget.setGeometry(QtCore.QRect(0, 160, 291, 861))
        self.listWidget.setMinimumSize(QtCore.QSize(290, 860))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(parent=LPIApp)
        self.label.setGeometry(QtCore.QRect(460, 20, 631, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=LPIApp)
        self.line.setGeometry(QtCore.QRect(290, 113, 821, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(parent=LPIApp)
        self.label_2.setGeometry(QtCore.QRect(430, 120, 541, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 290, 371, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(106, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.CustMailWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget)
        self.CustMailWidget.setMaximumSize(QtCore.QSize(257, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.CustMailWidget.setFont(font)
        self.CustMailWidget.setAcceptDrops(False)
        self.CustMailWidget.setReadOnly(True)
        self.CustMailWidget.setObjectName("CustMailWidget")
        self.horizontalLayout_2.addWidget(self.CustMailWidget)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_2.setGeometry(QtCore.QRect(510, 170, 331, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(160, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.DateINWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_2)
        self.DateINWidget.setMaximumSize(QtCore.QSize(163, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.DateINWidget.setFont(font)
        self.DateINWidget.setAcceptDrops(False)
        self.DateINWidget.setReadOnly(True)
        self.DateINWidget.setObjectName("DateINWidget")
        self.horizontalLayout_3.addWidget(self.DateINWidget)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_3.setGeometry(QtCore.QRect(700, 290, 371, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_7.setMaximumSize(QtCore.QSize(118, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.CustTelWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_3)
        self.CustTelWidget.setMaximumSize(QtCore.QSize(245, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.CustTelWidget.setFont(font)
        self.CustTelWidget.setAcceptDrops(False)
        self.CustTelWidget.setReadOnly(True)
        self.CustTelWidget.setObjectName("CustTelWidget")
        self.horizontalLayout_4.addWidget(self.CustTelWidget)
        self.layoutWidget_4 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_4.setGeometry(QtCore.QRect(310, 250, 611, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.label_8.setMinimumSize(QtCore.QSize(106, 0))
        self.label_8.setMaximumSize(QtCore.QSize(106, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.CustNameWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_4)
        self.CustNameWidget.setMaximumSize(QtCore.QSize(500, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.CustNameWidget.setFont(font)
        self.CustNameWidget.setAcceptDrops(False)
        self.CustNameWidget.setReadOnly(True)
        self.CustNameWidget.setObjectName("CustNameWidget")
        self.horizontalLayout_5.addWidget(self.CustNameWidget)
        self.layoutWidget_5 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_5.setGeometry(QtCore.QRect(420, 340, 561, 32))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.label_9.setMaximumSize(QtCore.QSize(560, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(parent=self.layoutWidget_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.layoutWidget_6 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_6.setGeometry(QtCore.QRect(310, 380, 201, 41))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.EknNumWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_6)
        self.EknNumWidget.setMaximumSize(QtCore.QSize(160, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.EknNumWidget.setFont(font)
        self.EknNumWidget.setAcceptDrops(False)
        self.EknNumWidget.setReadOnly(True)
        self.EknNumWidget.setObjectName("EknNumWidget")
        self.horizontalLayout_6.addWidget(self.EknNumWidget)
        self.layoutWidget_7 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_7.setGeometry(QtCore.QRect(520, 380, 591, 41))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.IdentNumWidget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_7)
        self.IdentNumWidget.setMaximumSize(QtCore.QSize(400, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.IdentNumWidget.setFont(font)
        self.IdentNumWidget.setAcceptDrops(False)
        self.IdentNumWidget.setReadOnly(True)
        self.IdentNumWidget.setObjectName("IdentNumWidget")
        self.horizontalLayout_7.addWidget(self.IdentNumWidget)
        self.layoutWidget_8 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_8.setGeometry(QtCore.QRect(420, 480, 561, 32))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.label_12.setMaximumSize(QtCore.QSize(560, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.line_4 = QtWidgets.QFrame(parent=self.layoutWidget_8)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.layoutWidget_9 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_9.setGeometry(QtCore.QRect(310, 420, 801, 31))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget_9)
        self.label_13.setMaximumSize(QtCore.QSize(132, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.EknNum_2 = QtWidgets.QPlainTextEdit(parent=self.layoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EknNum_2.sizePolicy().hasHeightForWidth())
        self.EknNum_2.setSizePolicy(sizePolicy)
        self.EknNum_2.setMaximumSize(QtCore.QSize(661, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.EknNum_2.setFont(font)
        self.EknNum_2.setAcceptDrops(False)
        self.EknNum_2.setReadOnly(True)
        self.EknNum_2.setObjectName("EknNum_2")
        self.horizontalLayout_8.addWidget(self.EknNum_2)
        self.layoutWidget1 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 170, 185, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(106, 29))
        self.label_3.setMaximumSize(QtCore.QSize(106, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.IncIDWidjget = QtWidgets.QPlainTextEdit(parent=self.layoutWidget1)
        self.IncIDWidjget.setMaximumSize(QtCore.QSize(71, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.IncIDWidjget.setFont(font)
        self.IncIDWidjget.setAcceptDrops(False)
        self.IncIDWidjget.setReadOnly(True)
        self.IncIDWidjget.setObjectName("IncIDWidjget")
        self.horizontalLayout.addWidget(self.IncIDWidjget)
        self.layoutWidget2 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget2.setGeometry(QtCore.QRect(420, 220, 561, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_5.setMaximumSize(QtCore.QSize(560, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(parent=self.layoutWidget2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.AdditionalnfoWidget = QtWidgets.QPlainTextEdit(parent=LPIApp)
        self.AdditionalnfoWidget.setGeometry(QtCore.QRect(320, 670, 780, 270))
        self.AdditionalnfoWidget.setMaximumSize(QtCore.QSize(780, 270))
        self.AdditionalnfoWidget.setReadOnly(True)
        self.AdditionalnfoWidget.setObjectName("AdditionalnfoWidget")
        self.layoutWidget_10 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget_10.setGeometry(QtCore.QRect(420, 620, 561, 32))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget_10)
        self.label_14.setMaximumSize(QtCore.QSize(560, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.line_5 = QtWidgets.QFrame(parent=self.layoutWidget_10)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.label_15 = QtWidgets.QLabel(parent=LPIApp)
        self.label_15.setGeometry(QtCore.QRect(0, 110, 290, 50))
        self.label_15.setMinimumSize(QtCore.QSize(290, 50))
        self.label_15.setMaximumSize(QtCore.QSize(290, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.layoutWidget3 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget3.setGeometry(QtCore.QRect(320, 530, 674, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CombGOSTButton = QtWidgets.QRadioButton(parent=self.layoutWidget3)
        self.CombGOSTButton.setMinimumSize(QtCore.QSize(220, 0))
        self.CombGOSTButton.setMaximumSize(QtCore.QSize(220, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.CombGOSTButton.setFont(font)
        self.CombGOSTButton.setCheckable(False)
        self.CombGOSTButton.setObjectName("CombGOSTButton")
        self.horizontalLayout_9.addWidget(self.CombGOSTButton)
        self.CombLookButton = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.CombLookButton.setMinimumSize(QtCore.QSize(220, 0))
        self.CombLookButton.setMaximumSize(QtCore.QSize(220, 21))
        self.CombLookButton.setObjectName("CombLookButton")
        self.horizontalLayout_9.addWidget(self.CombLookButton)
        self.CombAddButton = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.CombAddButton.setMinimumSize(QtCore.QSize(220, 0))
        self.CombAddButton.setMaximumSize(QtCore.QSize(220, 21))
        self.CombAddButton.setObjectName("CombAddButton")
        self.horizontalLayout_9.addWidget(self.CombAddButton)
        self.layoutWidget4 = QtWidgets.QWidget(parent=LPIApp)
        self.layoutWidget4.setGeometry(QtCore.QRect(320, 560, 674, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.FlamGOSTButton = QtWidgets.QRadioButton(parent=self.layoutWidget4)
        self.FlamGOSTButton.setMinimumSize(QtCore.QSize(220, 0))
        self.FlamGOSTButton.setMaximumSize(QtCore.QSize(220, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.FlamGOSTButton.setFont(font)
        self.FlamGOSTButton.setObjectName("FlamGOSTButton")
        self.horizontalLayout_10.addWidget(self.FlamGOSTButton)
        self.FlamLookButton = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.FlamLookButton.setMinimumSize(QtCore.QSize(220, 0))
        self.FlamLookButton.setMaximumSize(QtCore.QSize(220, 21))
        self.FlamLookButton.setObjectName("FlamLookButton")
        self.horizontalLayout_10.addWidget(self.FlamLookButton)
        self.FlamAddButton = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.FlamAddButton.setMinimumSize(QtCore.QSize(220, 0))
        self.FlamAddButton.setMaximumSize(QtCore.QSize(220, 21))
        self.FlamAddButton.setObjectName("FlamAddButton")
        self.horizontalLayout_10.addWidget(self.FlamAddButton)

        self.retranslateUi(LPIApp)
        QtCore.QMetaObject.connectSlotsByName(LPIApp)

    def retranslateUi(self, LPIApp):
        _translate = QtCore.QCoreApplication.translate
        LPIApp.setWindowTitle(_translate("LPIApp", "LPI TN"))
        self.label.setText(_translate("LPIApp", "Лаборатория пожарных испытаний СБЕ ПМиПИР"))
        self.label_2.setText(_translate("LPIApp", "Общая информация о заявке"))
        self.label_4.setText(_translate("LPIApp", "Почта заказчика"))
        self.label_6.setText(_translate("LPIApp", "Дата поступления заявки:"))
        self.label_7.setText(_translate("LPIApp", "Телефон заказчика"))
        self.label_8.setText(_translate("LPIApp", "ФИО заказчика:"))
        self.label_9.setText(_translate("LPIApp", "Информация об объекте исследования"))
        self.label_10.setText(_translate("LPIApp", "ЕКН:"))
        self.label_11.setText(_translate("LPIApp", "Идентификатор (№ партии):"))
        self.label_12.setText(_translate("LPIApp", "Информация о предмете исследования"))
        self.label_13.setText(_translate("LPIApp", "Название материала:"))
        self.label_3.setText(_translate("LPIApp", "№ заявки"))
        self.label_5.setText(_translate("LPIApp", "Информация о заказчике"))
        self.label_14.setText(_translate("LPIApp", "Дополнительная информация от заказчика"))
        self.label_15.setText(_translate("LPIApp", "Перечень заявок"))
        self.CombGOSTButton.setText(_translate("LPIApp", "Метод 2 ГОСТ 30244"))
        self.CombLookButton.setText(_translate("LPIApp", "Смотреть/редактировать результаты"))
        self.CombAddButton.setText(_translate("LPIApp", "Внести результаты"))
        self.FlamGOSTButton.setText(_translate("LPIApp", "ГОСТ 30402"))
        self.FlamLookButton.setText(_translate("LPIApp", "Смотреть/редактировать результаты"))
        self.FlamAddButton.setText(_translate("LPIApp", "Внести результаты"))





class Ui_LPIApp(Ui_LPIApp):
    def setupUi(self, LPIApp):
        super().setupUi(LPIApp)

        # Дополнительные настройки интерфейса
        self.listWidget.itemClicked.connect(self.load_request_data)
        self.CombGOSTButton.setCheckable(False)
        self.FlamGOSTButton.setCheckable(False)

        # Добавляем обработчик двойного клика (новый код)
        self.listWidget.itemDoubleClicked.connect(self.on_double_click)

    def on_double_click(self, item):
        """Улучшенная версия с форматированием вывода"""
        if not hasattr(self, 'df') or self.df.empty:
            QMessageBox.warning(self.LPIApp, "Ошибка", "Нет данных для отображения")
            return

        row_idx = self.listWidget.row(item)
        if 0 <= row_idx < len(self.df):
            row = self.df.iloc[row_idx]

            # Форматируем вывод для лучшей читаемости
            info = "\n".join([f"{col}: {val}" for col, val in row.items()])

            msg = QMessageBox(self.LPIApp)
            msg.setWindowTitle("Полная информация")
            msg.setText(info)
            msg.setStandardButtons(QMessageBox.StandardButton.Ok)
            msg.exec()

    def load_data_from_dataframe(self, df: pd.DataFrame):
        """Загружает данные из DataFrame в интерфейс"""
        self.df = df

        # Очищаем список заявок
        self.listWidget.clear()

        # Заполняем список заявок (пример: колонка '№ заявки')
        if not df.empty:
            for _, row in df.iterrows():
                # Формируем строку для отображения (можно настроить под свои колонки)
                item_text = f"{row.get('№ заявки', '')} | {row.get('ФИО заказчика', '')}"
                self.listWidget.addItem(item_text)

    def load_request_data(self, item):
        """Загружает данные выбранной заявки в поля формы"""
        if not hasattr(self, 'df') or self.df.empty:
            return

        # Находим индекс выбранной строки
        row_idx = self.listWidget.row(item)
        if row_idx < 0 or row_idx >= len(self.df):
            return

        row = self.df.iloc[row_idx]

        try:
            # Заполняем основные поля
            self.IncIDWidjget.setPlainText(str(row.get('№ заявки', '')))
            self.CustNameWidget.setPlainText(str(row.get('ФИО заказчика', '')))
            self.CustMailWidget.setPlainText(str(row.get('Почта заказчика', '')))
            self.CustTelWidget.setPlainText(str(row.get('Телефон заказчика', '')))
            self.DateINWidget.setPlainText(str(row.get('Дата поступления', '')))

            # Заполняем информацию об объекте
            self.EknNumWidget.setPlainText(str(row.get('ЕКН', '')))
            self.IdentNumWidget.setPlainText(str(row.get('Идентификатор', '')))
            self.EknNum_2.setPlainText(str(row.get('Название материала', '')))

            # Дополнительная информация
            self.AdditionalnfoWidget.setPlainText(str(row.get('Дополнительная информация', '')))

            # Управление индикаторами методов испытаний
            self.update_method_indicators(row)

        except Exception as e:
            QMessageBox.warning(self.LPIApp, "Ошибка", f"Не удалось загрузить данные: {str(e)}")

    def update_method_indicators(self, row):
        """Обновляет индикаторы методов испытаний"""
        # Пример логики для индикаторов (настройте под свои данные)
        comb_value = str(row.get('Метод 2 ГОСТ 30244', '')).strip().lower()
        flam_value = str(row.get('ГОСТ 30402', '')).strip().lower()

        # Устанавливаем стиль в зависимости от наличия данных
        self.set_indicator_style(self.CombGOSTButton, comb_value not in ['', 'нет', 'none'])
        self.set_indicator_style(self.FlamGOSTButton, flam_value not in ['', 'нет', 'none'])

    def set_indicator_style(self, indicator, is_active):
        """Устанавливает стиль индикатора"""
        if is_active:
            indicator.setStyleSheet("""
                QRadioButton {
                    color: green;
                    font-weight: bold;
                    text-decoration: underline;
                }
                QRadioButton::indicator {
                    background-color: green;
                    border: 1px solid darkgreen;
                }
            """)
        else:
            indicator.setStyleSheet("""
                QRadioButton {
                    color: red;
                    font-weight: bold;
                    text-decoration: underline;
                }
                QRadioButton::indicator {
                    background-color: red;
                    border: 1px solid darkred;
                }
            """)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_LPIApp()
    ui.setupUi(window)
    ui.load_data_from_dataframe(df)

    window.show()
    sys.exit(app.exec())